spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/botox
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: trace
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG