spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  data:
    redis:
      host: localhost
      port: 6379
      username: sa
      password:


logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: trace
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG

jwt:
  issuer: kim11
  secretKey: ff54dd1f64544befbeae0e43d1b9df54ff54dd1f64544befbeae0e43d1b9df54ff54dd1f64544befbeae0e43d1b9df54
