name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17 (Amazon Corretto)
        uses: actions/setup-java@v2
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: spring-app
          path: build/libs/*.jar

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: spring-app
          path: build/

      - name: SSH to Bastion and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.BASTION_USER }}
          key: ${{ secrets.BASTION_SSH_KEY }}
          script: |
            scp -i ~/.ssh/id_rsa build/spring-app.jar ${{ secrets.EC2_USER }}@10.0.4.8:/home/${{ secrets.EC2_USER }}/
            ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@10.0.4.8 "java -jar /home/${{ secrets.EC2_USER }}/spring-app.jar"
